#!/usr/bin/env bun
/**
 * Deterministic UI asset embedding generator.
 * 
 * Builds hub-ui and generates packages/hub/src/uiAssets.generated.ts
 * with embedded assets for serving at /ui/assets/*.
 * 
 * Determinism guarantees:
 * - Stable map key ordering (sorted by path)
 * - No timestamps or random values in generated code
 * - Content hashes are deterministic (from Vite build)
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { execSync } from "node:child_process";

const REPO_ROOT = join(import.meta.dir, "../../..");
const HUB_UI_DIR = join(REPO_ROOT, "packages/hub-ui");
const HUB_UI_DIST = join(HUB_UI_DIR, "dist");
const OUTPUT_FILE = join(REPO_ROOT, "packages/hub/src/uiAssets.generated.ts");

interface AssetEntry {
  path: string; // Relative path from dist/ (e.g., "assets/index-abc123.js")
  content: string; // Base64-encoded content
  contentType: string; // MIME type
}

/**
 * Build hub-ui with Vite.
 */
function buildHubUi(): void {
  console.log("Building hub-ui...");
  
  try {
    execSync("bun run build", {
      cwd: HUB_UI_DIR,
      stdio: "inherit",
    });
  } catch (err) {
    console.error("Failed to build hub-ui:", err);
    process.exit(1);
  }
  
  console.log("✓ hub-ui build complete");
}

/**
 * Determine MIME type from file extension.
 */
function getMimeType(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase();
  
  const mimeMap: Record<string, string> = {
    "html": "text/html; charset=utf-8",
    "js": "application/javascript; charset=utf-8",
    "css": "text/css; charset=utf-8",
    "json": "application/json; charset=utf-8",
    "svg": "image/svg+xml",
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
    "woff": "font/woff",
    "woff2": "font/woff2",
    "ttf": "font/ttf",
    "eot": "application/vnd.ms-fontobject",
  };
  
  return mimeMap[ext || ""] || "application/octet-stream";
}

/**
 * Recursively collect all files from a directory.
 */
function collectFiles(dir: string, baseDir: string = dir): string[] {
  const files: string[] = [];
  
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    
    if (stat.isDirectory()) {
      files.push(...collectFiles(fullPath, baseDir));
    } else if (stat.isFile()) {
      const relativePath = relative(baseDir, fullPath).replaceAll("\\", "/");
      files.push(relativePath);
    }
  }
  
  return files;
}

/**
 * Read and embed all assets from hub-ui/dist/.
 */
function embedAssets(): AssetEntry[] {
  if (!existsSync(HUB_UI_DIST)) {
    console.error("hub-ui/dist/ not found. Run build first.");
    process.exit(1);
  }
  
  const files = collectFiles(HUB_UI_DIST);
  const assets: AssetEntry[] = [];
  
  for (const file of files) {
    // Skip manifest.json (used for build-time asset discovery only)
    if (file === ".vite/manifest.json" || file === "manifest.json") {
      continue;
    }
    
    const fullPath = join(HUB_UI_DIST, file);
    const content = readFileSync(fullPath);
    const base64 = content.toString("base64");
    const contentType = getMimeType(file);
    
    assets.push({
      path: file,
      content: base64,
      contentType,
    });
  }
  
  // Sort by path for deterministic ordering (locale-independent)
  assets.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  
  console.log(`✓ Embedded ${assets.length} assets`);
  
  return assets;
}

/**
 * Resolve SPA shell path.
 *
 * Vite emits dist/index.html that references hashed JS/CSS assets.
 * We always serve this file as the shell for /ui routes.
 */
function findEntryHtml(): string | null {
  const indexPath = join(HUB_UI_DIST, "index.html");
  return existsSync(indexPath) ? "index.html" : null;
}

/**
 * Generate TypeScript module with embedded assets.
 */
function generateModule(assets: AssetEntry[]): string {
  const entryHtml = findEntryHtml();
  
  const lines: string[] = [];
  
  lines.push("/**");
  lines.push(" * GENERATED FILE - DO NOT EDIT");
  lines.push(" * ");
  lines.push(" * This file is generated by packages/hub/scripts/embedUi.ts");
  lines.push(" * Source: packages/hub-ui/dist/");
  lines.push(" * ");
  lines.push(" * To regenerate: bun run --cwd packages/hub ui:embed");
  lines.push(" */");
  lines.push("");
  lines.push("export interface UiAsset {");
  lines.push("  content: string; // Base64-encoded");
  lines.push("  contentType: string;");
  lines.push("}");
  lines.push("");
  lines.push("/**");
  lines.push(" * Map of asset paths to embedded content.");
  lines.push(" * Keys are relative paths from /ui/assets/ (e.g., 'index.js')");
  lines.push(" */");
  lines.push("export const UI_ASSETS = new Map<string, UiAsset>([");
  
  for (const asset of assets) {
    // Escape special characters in base64 content (backslashes, quotes)
    const escapedContent = asset.content.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    
    lines.push(`  ["${asset.path}", {`);
    lines.push(`    content: "${escapedContent}",`);
    lines.push(`    contentType: "${asset.contentType}",`);
    lines.push(`  }],`);
  }
  
  lines.push("]);");
  lines.push("");
  lines.push("/**");
  lines.push(" * Entry HTML file path (SPA shell).");
  lines.push(" */");
  lines.push(`export const UI_ENTRY_HTML = ${entryHtml ? `"${entryHtml}"` : "null"};`);
  lines.push("");
  
  return lines.join("\n");
}

/**
 * Main entry point.
 */
function main(): void {
  console.log("Embedding hub-ui assets...");
  console.log("");
  
  // Build hub-ui
  buildHubUi();
  console.log("");
  
  // Embed assets
  const assets = embedAssets();
  console.log("");
  
  // Generate module
  const tsCode = generateModule(assets);
  writeFileSync(OUTPUT_FILE, tsCode, "utf-8");
  
  console.log(`✓ Generated ${OUTPUT_FILE}`);
  console.log(`✓ Total assets: ${assets.length}`);
  console.log("");
  console.log("Done!");
}

main();
